### ISSUE TITLE
[HF2020 Contributor] vijay5158 / India

### ISSUE THREAD

**Issue by vijay5158** [mayadata-io/swag#17]
Here are the list of PRs that I have contributed for Hacktoberfest 2020:
- https://github.com/openebs/openebs/pull/3231
- https://github.com/openebs/openebs/pull/3242
- https://github.com/openebs/openebs/pull/3286
- https://github.com/openebs/openebs-docs/pull/886

I have submitted my shipping details at [https://forms.gle/sfeiKmrH35n1PWbQA](https://forms.gle/sfeiKmrH35n1PWbQA)

**Comment by kmova** [comment]
https://github.com/openebs/openebs-docs/pull/886
