### ISSUE TITLE
Michael Fornaro / Australia

### ISSUE THREAD

**Issue by akhilerm** [mayadata-io/swag#2]
OpenEBS contributor. 

Contributed the multiarch build for NDM and migration to github actions.

**Comment by akhilerm** [comment]
Address details shared with @NisantaSahoo

**Comment by NisantaSahoo** [comment]
@akhilerm do you have the contact number?

**Comment by NisantaSahoo** [comment]
Or you can ask the user to fill this form https://bit.ly/30AWPoN

**Comment by kmova** [comment]
Requested for details in slack. cc: @xUnholy

**Comment by xunholy** [comment]
Thanks, just filled the form out.

**Comment by NisantaSahoo** [comment]
Swag box was delivered on 14th Oct 2020
